services:
  web:
    image: docksaficio/monapp:${VERSION}
    ports:
      -  "8081:5000"


  db:
    image: postgres
    environment:
      POSTGRES_USER: moi
      POSTGRES_PASSWORD: mdp
      POSTGRES_DB: nomdelabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
